version: '3'

services:
  database: # Nom du service
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'

  MohaProjetCCI: # Nom du service
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'

  mailer:
    image: schickling/mailcatcher
    ports: 
      - 1025
      - 1080
